# Generated by Django 3.0.8 on 2020-07-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Player')),
                ('games_count', models.IntegerField(default=0)),
                ('wins_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='username'),
        ),
    ]
