# Generated by Django 3.0.8 on 2020-08-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_field_game_userstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='has_ships',
            field=models.BooleanField(default=False),
        ),
    ]
