# Generated by Django 3.0.8 on 2020-07-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200731_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistic',
            old_name='player',
            new_name='user',
        ),
    ]
