# Generated by Django 3.0.8 on 2020-08-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_field_has_ships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[(0, 'available'), (1, 'not_available'), (2, 'started'), (3, 'ended')], default='available', max_length=20),
        ),
    ]
