# Generated by Django 3.0.8 on 2020-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200821_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'available'), (1, 'not_available'), (2, 'started'), (3, 'ended')], default=0),
        ),
    ]
