# Generated by Django 3.0.8 on 2020-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200821_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('not_available', 'not_available'), ('started', 'started'), ('ended', 'ended')], default='available', max_length=20),
        ),
    ]
