# Generated by Django 3.0.8 on 2020-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_field_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('is_av', 'is_available'), ('is_st', 'is_started'), ('is_en', 'is_ended')], default='is_av', max_length=20),
        ),
    ]
