# Generated by Django 3.0.8 on 2020-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200821_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('preparing', 'preparing'), ('started', 'started'), ('ended', 'ended')], default='available', max_length=20),
        ),
    ]
