# Generated by Django 3.0.8 on 2020-08-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('av', 'available'), ('st', 'started'), ('en', 'ended')], default='is_av', max_length=20),
        ),
    ]
