# Generated by Django 3.0.8 on 2020-08-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200805_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=10),
        ),
    ]
