# Generated by Django 3.0.8 on 2020-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_userstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='can_move',
            field=models.BooleanField(default=False),
        ),
    ]
